name: Main

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    tags:        
      - v0.*           
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create log-file in `/var/log`
        run: |
          sudo touch /var/log/dfcti_system_logs.log
          sudo chown 777 /var/log/dfcti_system_logs.log
          ls -l
          ls -l /var/log/
      - name: Create release with artifact | Deliver log-file
        uses: softprops/action-gh-release@v1
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            ./python/Pipfile
            CHANGELOG.md
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./log-reader/dfcti_log_reader.py