name: Main

on:
  push:
    tags:        
      - v*           
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
    

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv for Python
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Create log-file in /var/log
        run: |
          sudo touch /var/log/dfcti_system_logs.log
          sudo chmod 777 /var/log/dfcti_system_logs.log

      - name: Install packages for log-reader script + give permission
        run: |
          cd log-reader
          pipenv install
          chmod +x dfcti_log_reader.py
      
      - name: Install packages for log-writer script + give permission
        run: |
          cd log-writer
          pipenv install
          chmod +x dfcti_log_writer.py

      - name: Start generating log lines in the background
        run: |
          cd log-writer
          nohup pipenv run python dfcti_log_writer.py &
      
      - name: Run the python log-reader script
        run: |
          ps aux | grep python
          pipenv run python dfcti_log_reader.py

      - name: Create release | Deliver log-file
        uses: softprops/action-gh-release@v1
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release `url`
        id: get_release_url
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}      

      - name: Create py-log-writer package
        run: |
          sudo apt-get install zip gzip tar
          zip -r py_log_writer.zip log-writer
      
      - name: Create py-log-reader package
        run: |
          zip -r py_log_reader.zip log-reader

      - name: Upload py-log-writer artifact
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: py_log_writer.zip
          asset_name: py_log_writer.zip
          asset_content_type: application/zip
          upload_url: ${{ steps.get_release_url.outputs.upload_url }}
      
      - name: Upload py-log-reader artifact
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: py_log_reader.zip
          asset_name: py_log_reader.zip
          asset_content_type: application/zip
          upload_url: ${{ steps.get_release_url.outputs.upload_url }}