# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv for Python
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Install packages
      run: |
        cd log-writer
        ls
        pipenv install

    - name: Create log-file
      run: |
        sudo touch /var/log/dfcti_cpu_logs.log
        sudo chmod 777 /var/log/dfcti_cpu_logs.log
        
    - name: Run the python log-writer script
      run: |
        cd log-writer
        pipenv run python dfcti_log_writer.py

    - name: Build
      run: |
        echo ${{github.sha}} > Release.txt
        echo $${{github.job}}> Release.txt
        echo $${{github.ref}}> Release.txt
        echo $${{github.repository}}> Release.txt
        echo $${{github.repository_owner}}> Release.txt
        echo $${{github.run_id}}> Release.txt
        echo $${{github.run_number}}> Release.txt
        echo $${{github.sha}}> Release.txt
        echo $${{github.token}}> Release.txt

    - name: Test
      run: cat Release.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: system-logs
        path: /var/log/dfcti_cpu_logs.log